# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e3973712ad0d94e5f6ec14ee6b5c7cdb4d4593412558061b2629b60c24a3fec40dae959a2eaa7c9cec4fb6b009552f722ac6289edda8f62e7c42118b90e0bc

test:
  secret_key_base: 869ef971155fef54f13232cbbfe8402db3879da3799caa08c6dde298b5099ae2aedffefde5fae895afc3664a0b89c18fd8cbeaa2e83427a2d53d8deb700c3324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
